### ISSUE TITLE
Queue brightness?

### ISSUE THREAD

**Issue by jack0233** [link07/Dark-Crunchyroll-Plugin-Chrome#1]
is it just me, or is those arrows really bright?
![lol](https://cloud.githubusercontent.com/assets/20768753/19401586/617f0e62-925c-11e6-92db-273aab59a5b4.png)

**Comment by link07** [comment]
I've never actually used the queue page, give me a few to fix it and I'll have a updated version on the chrome store.  Thanks!

**Comment by link07** [comment]
As soon as the chrome store publishes 1.1.6, it should be themed better.

The new version looks like this: http://i.imgur.com/txnFcXG.png.

Thanks for letting me know, and let me know if you find any other issues!
