### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by jemorg2316** [link07/Dark-Crunchyroll-Plugin-Chrome#2]
After going through a few videos on crunchyroll, the page turns mostly white, with some of the dark plugin still affecting it. Is there anyway to fix this issue.

**Comment by link07** [comment]
Can you take a screenshot?  I have a feeling a tag is getting changed somewhere, but I've never run into the issue myself.

**Comment by jemorg2316** [comment]
On Thursday, April 13, 2017 10:27 PM, Tyler <notifications@github.com> wrote:
 

 Can you take a screenshot? I have a feeling a tag is getting changed somewhere, but I've never run into the issue myself.—

**Comment by link07** [comment]
I uploaded an attempt to fix this to the chrome store, as soon as it pushes version 1.2.1 it should (hopefully) be fixed.  Let me know if your still having the issue.

**Comment by link07** [comment]
I'm going to assume that this was fixed when #3 was fixed, please let me know if there is any other missing theme / if it wasn't fixed it.
